Repository balfoldi/Easy-Riding, pull requests merged in 2020-12, with the labels that each got.

#22 Mise en place de l'app Fullstack !
  .browserslistrc
  Gemfile
  Gemfile.lock
  app/controllers/front_app_controller.rb
  app/javascript/packs/components/ExampleComponent/index.jsx
  app/javascript/packs/index.jsx
  app/javascript/packs/index.scss
  app/views/front_app/react.html.erb
  babel.config.js
  bin/webpack
  bin/webpack-dev-server
  config/routes.rb
  config/webpack/development.js
  config/webpack/environment.js
  config/webpack/production.js
  config/webpack/test.js
  config/webpacker.yml
  package.json
  postcss.config.js
  yarn.lock
Labels: back, front

#30 code for relation insersion in response
  app/controllers/application_controller.rb
  app/controllers/bikes_controller.rb
  app/models/application_record.rb
  app/models/bike.rb
  config/routes.rb
Labels: back

#36 Feature/lp
  app/javascript/packs/components/BreadCrumb/index.jsx
  app/javascript/packs/components/FooterMain/footermain.scss
  app/javascript/packs/components/FooterMain/index.jsx
  app/javascript/packs/components/JumboHome/jumbohome.scss
  app/javascript/packs/components/LoginForm/index.jsx
  app/javascript/packs/components/NavMain/index.jsx
  app/javascript/packs/components/NavMain/navmain.scss
  app/javascript/packs/components/SignupForm/index.jsx
  app/javascript/packs/index.jsx
  app/javascript/packs/index.scss
  app/javascript/packs/pages/Home.jsx
  app/javascript/packs/pages/Login.jsx
  app/javascript/packs/pages/Signup.jsx
Labels: front

#40 ajoute le react-router
  app/javascript/packs/components/FooterMain/index.jsx
  app/javascript/packs/components/JumboHome/index.jsx
  app/javascript/packs/components/NavMain/index.jsx
  app/javascript/packs/index.jsx
  app/javascript/packs/pages/Offers.jsx
  app/javascript/packs/pages/Profile.jsx
Labels: front

#44 Feature/forms
  app/javascript/packs/components/LoginForm/index.jsx
  app/javascript/packs/components/LoginForm/loginform.scss
  app/javascript/packs/components/SignupForm/index.jsx
  app/javascript/packs/components/SignupForm/signupform.scss
  app/javascript/packs/index.jsx
  app/javascript/packs/pages/Login.jsx
  app/javascript/packs/pages/Signup.jsx
Labels: front

#50 signup form fix
  app/javascript/packs/components/SignupForm/index.jsx
  app/javascript/packs/components/SignupForm/signupform.scss
Labels: front

#51 Ajoute sous-routeur page utilisateur
  app/javascript/packs/components/ExampleComponent/index.jsx
  app/javascript/packs/components/Favorites/index.jsx
  app/javascript/packs/components/Garage/index.jsx
  app/javascript/packs/components/JumboHome/index.jsx
  app/javascript/packs/components/JumboHome/jumbohome.scss
  app/javascript/packs/components/MyBookings/index.jsx
  app/javascript/packs/components/MyOffers/index.jsx
  app/javascript/packs/components/NavMain/index.jsx
  app/javascript/packs/components/NavProfile/index.jsx
  app/javascript/packs/components/ProfileInfo/index.jsx
  app/javascript/packs/index.jsx
  app/javascript/packs/pages/Profile.jsx
Labels: front

#59 everything should work
  app/javascript/packs/components/Calendar/index.jsx
  app/javascript/packs/components/LoginForm/index.jsx
  app/javascript/packs/components/assets/img/firethenavbar.jpg
  app/javascript/packs/components/layout/BreadCrumb/index.jsx
  app/javascript/packs/components/layout/FooterMain/index.jsx
  app/javascript/packs/components/layout/FooterMain/index.scss
  app/javascript/packs/components/layout/NavMain/index.jsx
  app/javascript/packs/components/layout/NavMain/index.scss
  app/javascript/packs/index.jsx
  app/javascript/packs/pages/Home.jsx
  app/javascript/packs/pages/Home/HeaderImage/dist/index.css
  app/javascript/packs/pages/Home/HeaderImage/firethenavbar.jpg
  app/javascript/packs/pages/Home/HeaderImage/index.jsx
  app/javascript/packs/pages/Home/HeaderImage/index.scss
  app/javascript/packs/pages/Home/HeaderImage/logo.png
  app/javascript/packs/pages/Home/Jumbo/CountryMap/index.jsx
  app/javascript/packs/pages/Home/Jumbo/CountryMap/index.scss
  app/javascript/packs/pages/Home/Jumbo/SearchButton/index.jsx
  app/javascript/packs/pages/Home/Jumbo/SearchButton/index.scss
  app/javascript/packs/pages/Home/Jumbo/france.png
  app/javascript/packs/pages/Home/Jumbo/index.jsx
  app/javascript/packs/pages/Home/Jumbo/index.scss
  app/javascript/packs/pages/Home/index.jsx
  app/javascript/packs/pages/Home/index.scss
  app/javascript/packs/pages/Login/LoginForm/index.jsx
  app/javascript/packs/pages/Login/LoginForm/index.scss
  app/javascript/packs/pages/Login/index.jsx
  app/javascript/packs/pages/NotFound/index.jsx
  app/javascript/packs/pages/Offer/AsideUser/index.jsx
  app/javascript/packs/pages/Offer/OfferBlock/index.jsx
  app/javascript/packs/pages/Offer/index.jsx
  app/javascript/packs/pages/Offers/AsideBar/index.jsx
  app/javascript/packs/pages/Offers/BikeList/BikeCard/index.jsx
  app/javascript/packs/pages/Offers/BikeList/index.jsx
  app/javascript/packs/pages/Offers/SearchBar/index.jsx
  app/javascript/packs/pages/Offers/SearchBar/searchbar.scss
  app/javascript/packs/pages/Offers/index.jsx
  app/javascript/packs/pages/Profile/Favorites/index.jsx
  app/javascript/packs/pages/Profile/Garage/BikeModal/index.jsx
  app/javascript/packs/pages/Profile/Garage/index.jsx
  app/javascript/packs/pages/Profile/MyBookings/BookingModal/index.jsx
  app/javascript/packs/pages/Profile/MyBookings/index.jsx
  app/javascript/packs/pages/Profile/MyOffers/OfferModal/index.jsx
  app/javascript/packs/pages/Profile/MyOffers/index.jsx
  app/javascript/packs/pages/Profile/NavProfile/index.jsx
  app/javascript/packs/pages/Profile/ProfileInfo/index.jsx
  app/javascript/packs/pages/Profile/index.jsx
  app/javascript/packs/pages/Signup/SignupForm/index.jsx
  app/javascript/packs/pages/Signup/SignupForm/signupform.scss
  app/javascript/packs/pages/Signup/index.jsx
  app/views/front_app/react.html.erb
  config/locales/active_record.fr.yml
  config/locales/devise.fr.yml
Labels: bug

#64 no header image no scroll to top
  app/javascript/packs/index.jsx
  app/javascript/packs/pages/Home/HeaderImage/index.css
  app/javascript/packs/pages/Home/HeaderImage/index.scss
  app/javascript/packs/pages/Home/index.jsx
Labels: front

#66 scss structure ok
  app/javascript/packs/index.scss
  app/javascript/packs/pages/Home/HeaderImage/index.scss
  app/javascript/packs/pages/Home/Jumbo/index.scss
  app/javascript/packs/pages/Home/index.scss
  app/javascript/packs/pages/Login/LoginForm/index.scss
  app/javascript/packs/pages/Offers/SearchBar/searchbar.scss
  app/javascript/packs/pages/Signup/SignupForm/signupform.scss
  app/javascript/packs/variables.scss
Labels: front

#72 suppression imports inutilisés
  app/javascript/packs/pages/Offers/AsideBar/index.jsx
  app/javascript/packs/pages/Offers/BikeList/index.jsx
  app/javascript/packs/pages/Offers/SearchBar/index.jsx
  app/javascript/packs/pages/Offers/SearchBar/index.scss
  app/javascript/packs/pages/Offers/index.jsx
Labels: bug

#70 Crée un AuthStore (MobX) et la partie login #48
  app/javascript/packs/index.jsx
  app/javascript/packs/pages/Login/LoginForm/index.jsx
  app/javascript/packs/stores/Auth.js
  db/seeds.rb
Labels: front

#78 Nettoie le stockage du token dans les cookies
  app/javascript/packs/stores/Auth.js
Labels: front

#77 Résout des problèmes de liens (style et balisage) #76
  app/javascript/packs/components/layout/NavMain/index.jsx
Labels: front

#82 Correction footer + nettoyage seed
  app/javascript/packs/components/layout/FooterMain/index.jsx
  app/javascript/packs/components/layout/FooterMain/index.scss
  db/seeds.rb
Labels: back, bug, front

#86 Feature/offers comp
  app/javascript/packs/index.scss
  app/javascript/packs/pages/Home/Jumbo/index.jsx
  app/javascript/packs/pages/Offers/BikeList/BikeCard/index.jsx
  app/javascript/packs/pages/Offers/BikeList/BikeCard/index.scss
  app/javascript/packs/pages/Offers/BikeList/index.jsx
  app/javascript/packs/pages/Offers/index.jsx
  app/javascript/packs/pages/Offers/moto.jpg
  app/javascript/packs/pages/Profile/index.jsx
  app/javascript/packs/pages/Profile/index.scss
Labels: front

#100 Bug | Ajoute l'import manquant
  app/javascript/packs/components/layout/BreadCrumb/index.jsx
Labels: bug

#99 Ajoute inscription, connexion et déconnexion
  app/javascript/packs/components/layout/NavMain/index.jsx
  app/javascript/packs/index.jsx
  app/javascript/packs/pages/Login/LoginForm/index.jsx
  app/javascript/packs/pages/Profile/index.jsx
  app/javascript/packs/pages/Signup/SignupForm/index.jsx
  app/javascript/packs/pages/Signup/SignupForm/index.scss
  app/javascript/packs/pages/TermsOfService/index.jsx
  app/javascript/packs/stores/Auth.js
  app/models/user.rb
Labels: front

#98 Feature/profiletab
  app/javascript/packs/components/layout/BreadCrumb/index.scss
  app/javascript/packs/pages/Offer/index.jsx
  app/javascript/packs/pages/Offer/index.scss
  app/javascript/packs/pages/Profile/index.jsx
  app/javascript/packs/pages/Profile/index.scss
Labels: front

#106 Ajoute la reconnexion automatique, affiche les alertes des validates à l'inscription et apporte plusieurs corrections
  app/javascript/packs/StoreProvider/index.jsx
  app/javascript/packs/components/layout/NavMain/index.jsx
  app/javascript/packs/index.jsx
  app/javascript/packs/pages/Home/Jumbo/index.jsx
  app/javascript/packs/pages/Login/LoginForm/index.jsx
  app/javascript/packs/pages/Profile/index.jsx
  app/javascript/packs/pages/Signup/SignupForm/index.jsx
  app/javascript/packs/stores/Auth.js
  config/locales/devise.fr.yml
  config/locales/en.yml
  config/routes.rb
  package.json
  yarn.lock
Labels: back, front

#109 Fix789
  app/javascript/packs/pages/Offers/index.jsx
  app/javascript/packs/pages/Profile/ProfileInfo/index.jsx
  app/javascript/packs/pages/Profile/ProfileInfo/index.scss
Labels: bug

#112 Ajoute la carte profil et une modale pour l'éditer
  FETCH_HEAD
  app/controllers/api/users_controller.rb
  app/javascript/packs/index.jsx
  app/javascript/packs/pages/Profile/ProfileInfo/ProfileModal/index.jsx
  app/javascript/packs/pages/Profile/ProfileInfo/ProfileModal/index.scss
  app/javascript/packs/pages/Profile/ProfileInfo/default_avatar.png
  app/javascript/packs/pages/Profile/ProfileInfo/index.jsx
  config/routes.rb
Labels: back, front

#118 Feature/profile
  app/javascript/packs/pages/Profile/ProfileInfo/ProfileModal/index.jsx
  app/javascript/packs/pages/Profile/ProfileInfo/index.jsx
  app/javascript/packs/pages/Profile/ProfileInfo/index.scss
Labels: front

#121 Simplifie la navbar
  app/javascript/packs/components/layout/NavMain/index.jsx
Labels: front

#127 Corrige le seed
  app/models/bike.rb
  app/models/offer.rb
  db/seeds.rb
Labels: back, bug

#131 Feature/profile
  app/controllers/bikes_controller.rb
  app/javascript/packs/pages/Profile/Garage/BikeShow/index.jsx
  app/javascript/packs/pages/Profile/Garage/BikeShow/index.scss
  app/javascript/packs/pages/Profile/Garage/index.jsx
  app/javascript/packs/pages/Profile/Garage/index.scss
  app/javascript/packs/pages/Profile/ProfileInfo/ProfileModal/index.jsx
  app/javascript/packs/pages/Profile/ProfileInfo/ProfileModal/index.scss
  app/javascript/packs/pages/Profile/ProfileInfo/index.jsx
  app/javascript/packs/pages/Profile/ProfileInfo/index.scss
  app/javascript/packs/variables.scss
  app/views/front_app/react.html.erb
Labels: front

#137 Corrige bug édition profil et retire les console.log
  app/controllers/api/users_controller.rb
  app/javascript/packs/pages/Offer/BookingModal/index.jsx
  app/javascript/packs/pages/Offer/index.jsx
  app/javascript/packs/pages/Offers/SearchBar/index.jsx
  app/javascript/packs/pages/Profile/Garage/BikeFormModal/PicturesInput/index.jsx
  app/javascript/packs/pages/Profile/Garage/BikeFormModal/index.jsx
  app/javascript/packs/pages/Profile/Garage/BikeShow/BikeEditFormModal/PicturesInput/index.jsx
  app/javascript/packs/pages/Profile/Garage/BikeShow/BikeEditFormModal/index.jsx
  app/javascript/packs/pages/Profile/Garage/BikeShow/index.jsx
  app/javascript/packs/pages/Profile/Garage/index.jsx
  app/javascript/packs/pages/Profile/MyBookings/BookingShow/index.jsx
  app/javascript/packs/pages/Profile/MyBookings/index.jsx
  app/javascript/packs/pages/Profile/MyOffers/OfferFormModal/MyBikeList/index.jsx
  app/javascript/packs/pages/Profile/MyOffers/OfferFormModal/index.jsx
  app/javascript/packs/pages/Profile/MyOffers/OfferShow/index.jsx
  app/javascript/packs/pages/Profile/MyOffers/index.jsx
  app/javascript/packs/pages/Profile/ProfileInfo/index.jsx
  app/javascript/packs/pages/Profile/index.jsx
Labels: bug, front

#138 whole card as a link
  app/javascript/packs/pages/Offers/BikeList/BikeCard/index.jsx
  app/javascript/packs/pages/Offers/BikeList/BikeCard/index.scss
Labels: front

#139 Corrige une propriété CSS et le bug du filtre des annonces
  app/javascript/packs/pages/Offers/BikeList/BikeCard/index.jsx
  app/javascript/packs/pages/Offers/index.jsx
Labels: bug, front

#147 Améliore le code, ajoute redirection Login avant réservation, ajoute une fonction minDate() pour les Bookings
  app/javascript/packs/pages/Offer/BookingModal/index.jsx
  app/javascript/packs/pages/Offer/index.jsx
  app/javascript/packs/pages/Offers/BikeList/BikeCard/dist/index.css
  app/javascript/packs/pages/Offers/BikeList/BikeCard/index.jsx
  app/javascript/packs/pages/Profile/MyOffers/OfferShow/index.jsx
  app/javascript/packs/stores/dist/Auth.dev.js
Labels: bug, enhancement, front

#150 Feature/front
  app/javascript/packs/pages/Profile/Garage/BikeShow/index.jsx
  app/javascript/packs/pages/Profile/Garage/BikeShow/index.scss
  app/javascript/packs/pages/Profile/Garage/index.jsx
  app/javascript/packs/pages/Profile/Garage/index.scss
  app/javascript/packs/pages/Profile/MyBookings/BookingShow/index.jsx
  app/javascript/packs/pages/Profile/MyBookings/BookingShow/index.scss
  app/javascript/packs/pages/Profile/MyBookings/index.jsx
  app/javascript/packs/pages/Profile/MyBookings/index.scss
  app/javascript/packs/pages/Profile/MyOffers/OfferShow/index.jsx
  app/javascript/packs/pages/Profile/MyOffers/OfferShow/index.scss
  app/javascript/packs/pages/Profile/MyOffers/index.jsx
  app/javascript/packs/pages/Profile/MyOffers/index.scss
  app/javascript/packs/pages/Profile/ProfileInfo/index.jsx
  app/javascript/packs/pages/Profile/ProfileInfo/index.scss
Labels: front

#156 solved
  app/javascript/packs/pages/Home/Jumbo/index.scss
  app/javascript/packs/variables.scss
Labels: front
